### ISSUE TITLE
Input styling clashes with plugins

### ISSUE THREAD

**Issue by aldendaniels** [jamiewilson/predawn#83] opened 2015-02-10 15:49 UTC
First - thanks so much for this gorgeous sublime theme. I've really enjoyed using Predawn.

I use the popular [SideBarEnhancements](https://github.com/titoBouzout/SideBarEnhancements) package for Sublime. When I use this to create a new file, the text input display appears to be messed up when using Predawn:

![screen shot 2015-02-10 at 9 47 01 am](https://cloud.githubusercontent.com/assets/4658558/6130275/ced31354-b109-11e4-97d7-be7f9caf14c0.png)

As you can see the input is pushed down and the text is being clipped. It's quite possible that this issue also affects other plugins besides SideBarEnhancements.

Cheers!

**Comment by aldendaniels** [comment] 2015-02-12 21:28
Update - this does affect other plugins. Here's the same issue with iOpener:

![screen shot 2015-02-12 at 3 28 04 pm](https://cloud.githubusercontent.com/assets/4658558/6177383/d1fbbda6-b2cb-11e4-9418-6ff90e455b88.png)

**Comment by trippo80** [comment] 2015-03-05 10:42
Just wanted to mention I've got the same issue with SideBarEnhancements. So I can confirm the issue exists.

**Comment by jamiewilson** [comment] 2015-03-07 18:14
Hey @aldendaniels and @trippo80, thanks for heads up. Could this be related to and fixed by the same method here: #8 ?

**Comment by trippo80** [comment] 2015-03-08 09:08
@jamiewilson @aldendaniels Hey - thanks for the tip. It seems to fix the issue for me.

Before resizing it looks like @aldendaniels screenshots above - but after resizing it looks like:

![image](https://cloud.githubusercontent.com/assets/848902/6545213/0ddcacf6-c57b-11e4-8f14-173b92c0698c.png)

So I would say that fixes the issue for me. Thanks again! (didn't know you could resize those elements of the editor)

**Comment by aldendaniels** [comment] 2015-03-09 16:34
@jamiewilson - Indeed - this fixes the issue. Thanks for the suggestion!

Obviously it's not ideal to have to manually resize 3rd party panes, but as Sublime remembers the resize across restart this is a perfectly workable solution.

**Closed** 2015-03-16 22:30 UTC
